ARGV = []
TRUE = true
FALSE = false
STDOUT = IO.new
STDIN = IO.new
STDERR = IO.new
ENV = {}
NIL = nil
RUBY_PATCHLEVEL = 112
RUBY_COPYRIGHT = 'ruby - Copyright (C) 1993-2016 Yukihiro Matsumoto'
TOPLEVEL_BINDING = Binding.new
RUBY_VERSION = '2.3.1'
RUBY_PLATFORM = 'x86_64-darwin15'
